global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'workers'
    static_configs:
      - targets: ['worker-1:8000', 'worker-2:8000', 'worker-3:8000']

  - job_name: 'providers'
    static_configs:
      - targets: ['gemini-mock:8000', 'openrouter-mock:8000']
